<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/drive/MyDrive/dataset/Emotion_Dataset/train.txt" , sep=';' , header=None , names=['text' , 'emotion'])

In [3]:
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [4]:
df.isnull().sum()

,0
text,0
emotion,0


In [5]:
unique_emotions = df['emotion'].unique()
emotion_number = {}
i = 0
for emotion in unique_emotions:
  emotion_number[emotion] = i
  i += 1

df['emotion'] = df['emotion'].map(emotion_number)
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [6]:
# step 1 = Covert into lower case
df['text'] = df['text'].apply(lambda x : x.lower())

In [7]:
# step 2 = remove punctuations
import string
def remove_punctuation(text):
  for punctuation in string.punctuation:
    text = text.replace(punctuation , '')
  return text

df['text'] = df['text'].apply(remove_punctuation)

In [8]:
# step 3 = remove numbers
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new

df['text'] = df['text'].apply(remove_numbers)

In [9]:
#step 4 = remove URL's & Links
def remove_links(text):
  import re
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

df['text'] = df['text'].apply(remove_links)

In [10]:
# step 5 = remove emojis
def remove_emojis(text):
  new = ""
  for i in text:
    if i.isascii():
      new += i

  return new

df['text'] = df['text'].apply(remove_emojis)

In [11]:
# step 6 = remove stopwords (is , am , the , are , that etc.)
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [12]:
stop_words = set(stopwords.words('english'))
def remove(text):
  words = text.split()
  cleaned = []
  for i in words:
    if i not in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [13]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [24]:
# Feature Extraction
# Technique 1 : Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizor = CountVectorizer(ngram_range = (1,3))

X = vectorizor.fit_transform(documents)

print("Vocabulary: " , vectorizor.get_feature_names_out())
print("\nBox Matrix: \n" , X.toarray())

Vocabulary:  ['best' 'great' 'is' 'is great' 'is the' 'is the best' 'love' 'love pasta'
 'love pizza' 'pasta' 'pasta is' 'pasta is great' 'pizza' 'pizza is'
 'pizza is the' 'the' 'the best']

Box Matrix: 
 [[0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0]]


In [26]:
# Technique 2 : TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizor = TfidfVectorizer()

X = vectorizor.fit_transform(documents)

print("Vocabulary: " , vectorizor.get_feature_names_out())
print("\nBox Matrix: \n" , X.toarray())

Vocabulary:  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

Box Matrix: 
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]


In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [29]:
X_train

,text
676,refers course though cant help feeling somehow...
12113,im starting feel im suffering fatigue
7077,feel like probably would liked book little bit...
13005,really feel awkward
12123,im feeling little grumpy today lame weather te...
...,...
13418,love leave reader feeling confused slightly de...
5390,feel delicate
860,starting feel little stressed
15795,feel stressed tired worn shape neglected


In [31]:
# Step 3 - Feature Extraction from dataset
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [33]:
# back of words
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [36]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)
pred_nb = nb_model.predict(X_test_bow)

print("Accuracy:", accuracy_score(y_test, pred_nb))
print("\nClassification Report:\n", classification_report(y_test, pred_nb))

Accuracy: 0.768125

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.63      0.74       427
           2       0.93      0.27      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200



In [38]:
# tf-idf
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)
pred_nb = nb2_model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, pred_nb))
print("\nClassification Report:\n", classification_report(y_test, pred_nb))

Accuracy: 0.6609375

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.93      0.80       946
           1       0.93      0.29      0.44       427
           2       1.00      0.03      0.06       296
           3       1.00      0.01      0.02       113
           4       0.92      0.22      0.36       397
           5       0.60      0.99      0.74      1021

    accuracy                           0.66      3200
   macro avg       0.86      0.41      0.40      3200
weighted avg       0.76      0.66      0.58      3200



In [39]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf, y_train)
pred_logistic = logistic_model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, pred_logistic))

Accuracy: 0.8628125
