<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra in NumPy**

In [1]:
import numpy as np

A = np.array([[6,1,1],
              [4,-2,5],
              [2,8,7]])

print("\nRank of A:" , np.linalg.matrix_rank(A))
print("\nTrace of A:" , np.trace(A))
print("\nDeterminant of A:\n" , np.linalg.det(A))
print("\nInver of A:\n" , np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n" , np.linalg.matrix_power(A,3))


Rank of A: 3

Trace of A: 11

Determinant of A:
 -306.0

Inver of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [2]:
#cofficient
a = np.array([[1,2] , [3,4]])
#constants
b = np.array([8,18])

print("Solution of linear equation:" , np.linalg.solve(a , b))

Solution of linear equation: [2. 3.]


In [3]:
#The Dot product is written using a central dot:
#a . b
#This means the Dot Product of a and b
#We can calculate the Dot Product of two vectors this way
#dot product magnitudes and angle
#a . b = |a| * |b| * cos(θ)

product = np.dot(5 , 4)
print("Dot product of scalar values: " , product)
vector_a = 12
vector_b = 4
product = np.dot(vector_a , vector_b)
print("Dot product of two vectors: " , product)

Dot product of scalar values:  20
Dot product of two vectors:  48


In [6]:
#This function return the dot product of the two vectors. If the argument is complex , then its conjugate id used for dot product
#if the argument id is multi-dimensional array, it is flattened

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Dot product of a & b:\n" ,np.dot(a, b))
print("\nVector product of a & b:\n" ,np.vdot(a, b)) #(1*5 + 2*6 + 3*7 + 4*8) = 70

a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])

print("\nDot product of a & b:\n" ,np.dot(a, b)) #(1+2j)(5+6j) + (3+4j)(7+8j)
print("\nVector product of a & b:\n" ,np.vdot(a, b)) #conj(a) · b




Dot product of a & b:
 [[19 22]
 [43 50]]

Vector product of a & b:
 70

Dot product of a & b:
 (-18+68j)

Vector product of a & b:
 (70-8j)


In [7]:
#Inner product of two arrays
a = np.array([1,5,0])
b = np.array([2,4,-1])

print("Inner product of a & b:\n" ,np.inner(a, b)) # 1*2 + 5*4 + 0*(-1) = 22

Inner product of a & b:
 22


In [9]:
#Compute the Outer product of two vectors
x = np.array(['a' , 'b' , 'c'] , dtype=object)
np.outer(x , [1,2,3])#result[i][j] = x[i] * y[j]

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [10]:
#Matrix or vector norms
#This function is able to return one of eight different matrix norms , or one of an infinite
#number of vector norms (described below), depending on the value of ord parameter

from numpy import linalg as LA
a = np.arange(9) - 4
print(a)

b = a.reshape((3, 3))
print(b)


[-4 -3 -2 -1  0  1  2  3  4]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]


In [11]:
print(LA.norm(a))#sqrt((−4)^2+(−3)^2+⋯+4^2) = 7.745..
print(LA.norm(b))#sqrt((−4)^2+(−3)^2+⋯+4^2) = 7.745.. (same as above)
print(LA.norm(b , 'fro')) #same as above
print(LA.norm(a , np.inf)) #∥A∥∞ ​= max(∣ai​∣) -> max(4,3,2,1,0,1,2,3,4)=4
print(LA.norm(b , np.inf)) #∥B∥∞​=max(∑​∣bij​∣) -> Row 1: 4 + 3 + 2 = 9 , Row 2: 1 + 0 + 1 = 2 , Row 3: 2 + 3 + 4 = 9 -> max=9
print(LA.norm(a , -np.inf)) #∥A∥−∞​=min(∣ai​∣) -> min(4,3,2,1,0,1,2,3,4) = 0
print(LA.norm(b , -np.inf)) #∥B∥−∞​=min(j∑​∣bij​∣) -> Row 1: 9 , Row 2: 2 , Row 3: 9 -> min = 2

7.745966692414834
7.745966692414834
7.745966692414834
4.0
9.0
0.0
2.0


In [12]:
#Compute the conditional number of matrix
#This function is capable of returning the condition number using one if Eight different norms

from numpy import linalg as LA
a = np.array([[1,0,-1] , [0,1,0] , [1,0,1]])
a

array([[ 1,  0, -1],
       [ 0,  1,  0],
       [ 1,  0,  1]])

In [13]:
print(LA.cond(a))#cond(A)=∥A∥⋅∥A^−1∥ -> It measures numerical stability , Larger value ⇒ matrix is ill-conditioned
print(LA.cond(a , 'fro'))#condF​(A)=∥A∥F​⋅∥A^−1∥F​ , ∥A∥F​=sqrt(∑aij^2​)
print(LA.cond(a , np.inf))#∥A∥∞​=max(row sum) , Row 1: 1 + 0 + 1 = 2 , Row 2: 1 , Row3:2  =>  ∥A∥∞​=2
print(LA.cond(a , -np.inf))#∥A∥−∞​=min(row sum)=1
print(LA.cond(a , 1))#1-norm (Max column sum) , Col 1: 2 , Col 2: 1 , Col 3: 2 , ∥A∥1​=2
print(LA.cond(a , -1))#Min column sum norm
print(LA.cond(a , 2))#cond2​(A) = σmin/​σmax​​ = 1.414..
print(LA.cond(a , -2))#cond−2 ​= σmax/​σmin ​​= 0.7071..

1.4142135623730951
3.1622776601683795
2.0
1.0
2.0
1.0
1.4142135623730951
0.7071067811865475


**numpy.linalg.multi_dot** <br>
Compute the dot product of two or more arrays in single function call , while automatically selecting the fastest evaluation order

In [15]:
from numpy.linalg import multi_dot

#prepare some data
A = np.random.random((10000 , 100))
B = np.random.random((100 , 10000))
C = np.random.random((10000 , 5))
D = np.random.random((5 , 333))

#the actual dot multiplication
#A · B → (10000, 10000)
#(A·B) · C → (10000, 5)
#((A·B)·C) · D → (10000, 333)
print(multi_dot([A , B , C , D]))

[[406990.85799256 201488.73969262 253455.76124969 ... 152617.67438738
  429276.08906576 531992.97739436]
 [410643.85389203 203295.00403938 255731.40287536 ... 153995.838571
  433162.95031471 536782.30892092]
 [397925.48235636 196992.76669668 247807.46007368 ... 149212.86793154
  419741.15785273 520187.60821721]
 ...
 [362946.14397072 179685.30872443 226020.13395815 ... 136079.09105086
  382800.46338447 474441.42254848]
 [385442.61093335 190805.966606   240018.3051132  ... 144530.62355156
  406534.71774379 503841.97324831]
 [407950.89065378 201940.90462828 254039.84380796 ... 152979.16797132
  430283.10531077 533272.11406161]]


In [16]:
from numpy import linalg as LA
#creating an array
#function
a = np.array([[1,-2j] , [2j,5]])

print("Array is:\n" , a)

#Calculate the eign values
#Using eigh() function
c , d = LA.eigh(a)

print("Eign value is:\n" , c)
print("Eign value is:\n" , d)

Array is:
 [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eign value is:
 [0.17157288 5.82842712]
Eign value is:
 [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [17]:
from numpy import linalg as LA
#creating an array
#function
a = np.diag((1,2,3))

print("Array is:\n" , a)

#Calculate the eign values
#Using eigh() function
c , d = LA.eigh(a)

print("Eign value is:\n" , c)
print("Eign value is:\n" , d)

Array is:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eign value is:
 [1. 2. 3.]
Eign value is:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
