<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Stacking: Several arrays can be stacked together along different axes**

np.vstack: To stack arrays along vertical axis <br>
np.hstack: To stack arrays along horizontal axis <br>
np.column_stack: To stack 1-D arrays as columns into 2-D arrays<br>
np.concatenate: To stack arrays on specified axis (axis is passed by argument)


In [2]:
import numpy as np

a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

#vertical stacking
print(np.vstack((a,b))) #merging the two arrays in vertical manner

#horizontal stacking
print(np.hstack((a,b))) #merging the two arrays in horizontal manner

#stacking columns
c = [10,5]
print(np.column_stack((a,c))) #stacking the columns

#contatenation method
print(np.concatenate((a,b),1)) #stacking along the axis 1 represent horizontal stacking & axis 0 reprsent vertical stacking


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 1  2 10]
 [ 3  4  5]]
[[1 2 5 6]
 [3 4 7 8]]


Splitting: For splitting we have these functions:

np.hsplit: Split array along horizontal axis<br>
np.vsplit: Split array along vertical axes<br>
np.array_split: Split array along specified axis

In [ ]:
a = np.array([[1,2,3,4,5,7],
              [8,7,6,5,9,4],
              [9,5,2,3,1,8],
              [3,4,5,6,7,1]])

#horizontal splitting
print(np.hsplit(a,3)) #Basically it split the arry along columns

#vertical splitting
print(np.vsplit(a,2)) #basically split the array along rows

[array([[1, 2],
       [8, 7],
       [9, 5],
       [3, 4]]), array([[3, 4],
       [6, 5],
       [2, 3],
       [5, 6]]), array([[5, 7],
       [9, 4],
       [1, 8],
       [7, 1]])]
[array([[1, 2, 3, 4, 5, 7],
       [8, 7, 6, 5, 9, 4]]), array([[9, 5, 2, 3, 1, 8],
       [3, 4, 5, 6, 7, 1]])]


In [ ]:
c = np.array([[1,2,3,4,5,6,7,8]]);
print(np.split(c,2, axis=1))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


## ***Broadcasting***
The term braodcasting describes how numoy treates arrays with different shapes during arithmatic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that thay have compatible shapes.

In [3]:
a = np.array([1.0,2.0,3.0])
b = 2.0
print(a*b)

c = [2.0,3.0,4.0]
print(a*c)

[2. 4. 6.]
[ 2.  6. 12.]


In [8]:

a = np.array([1.0,2.0,3.0,4.0])
b = np.array([0.0,1.0,2.0])

print(a[: , np.newaxis] + b)

'''
Understanding a[:, np.newaxis]
a[:, np.newaxis]


This means:

: → take all elements of a

np.newaxis → add a new column dimension

Before:
a.shape → (4,)

After:
a[:, np.newaxis].shape → (4, 1)


So a becomes:

[[1.],
 [2.],
 [3.],
 [4.]]


A column vector.

Now look at b
b.shape → (3,)


NumPy treats it like a row vector:

[0. 1. 2.]

Broadcasting during addition

Now NumPy does broadcasting:

a (4×1)	b (3,)	result
rows = 4	columns = 3	output = (4×3)

NumPy expands them to:

[[1.]      +  [0. 1. 2.]
 [2.]
 [3.]
 [4.]]
'''

[[1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]]


'\nUnderstanding a[:, np.newaxis]\na[:, np.newaxis]\n\n\nThis means:\n\n: → take all elements of a\n\nnp.newaxis → add a new column dimension\n\nBefore:\na.shape → (4,)\n\nAfter:\na[:, np.newaxis].shape → (4, 1)\n\n\nSo a becomes:\n\n[[1.],\n [2.],\n [3.],\n [4.]]\n\n\nA column vector.\n\nNow look at b\nb.shape → (3,)\n\n\nNumPy treats it like a row vector:\n\n[0. 1. 2.]\n\nBroadcasting during addition\n\nNow NumPy does broadcasting:\n\na (4×1)\tb (3,)\tresult\nrows = 4\tcolumns = 3\toutput = (4×3)\n\nNumPy expands them to:\n\n[[1.]      +  [0. 1. 2.]\n [2.]\n [3.]\n [4.]]\n'

In [9]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print(a)
print(b)
print(a + b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# **Data Time Working in Numpy**

In [10]:
#creating a date
today = np.datetime64('2017-02-12')
print("Date is:" , today)
print("Year is:" , np.datetime64(today, 'Y'))


Date is: 2017-02-12
Year is: 2017


In [14]:
#creating array of dates in a month
dates = np.arange('2017-02' , '2017-03' , dtype='datetime64[D]')
print("\nDates of February, 2017:\n" , dates)
print("\nToday is February:", today in dates)



Dates of February, 2017:
 ['2017-02-01' '2017-02-02' '2017-02-03' '2017-02-04' '2017-02-05'
 '2017-02-06' '2017-02-07' '2017-02-08' '2017-02-09' '2017-02-10'
 '2017-02-11' '2017-02-12' '2017-02-13' '2017-02-14' '2017-02-15'
 '2017-02-16' '2017-02-17' '2017-02-18' '2017-02-19' '2017-02-20'
 '2017-02-21' '2017-02-22' '2017-02-23' '2017-02-24' '2017-02-25'
 '2017-02-26' '2017-02-27' '2017-02-28']

Today is February: True


In [16]:
#arithmatic operation on dates
dur = np.datetime64('2017-05-22') - np.datetime64('2016-05-22')
print("\nNo. of days:", dur)
print("No. of weeks:", np.timedelta64(dur, 'W'))



No. of days: 365 days
No. of weeks: 52 weeks


In [17]:
#sorting dates
a = np.array(['2017-02-12' , '2016-10-13' , '2019-05-22'] , dtype='datetime64')
print("\nDates in sorted order:", np.sort(a))


Dates in sorted order: ['2016-10-13' '2017-02-12' '2019-05-22']
