<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/Numpy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mathematical Geometrical Functions**

In [4]:
#sin , cos , tan , sinh , cosh , tanh FUNCTIONS
#These functions is use to calculate the rrignometruc tangent for all the elements of the array passed as the argument
import numpy as np
import math
arr = np.array([1 , 2 , 3])
print(arr)
res = np.cos(arr)
print(res)
res = np.sin(arr)
print(res)
res = np.tan(arr)
print(res)

[1 2 3]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 1.55740772 -2.18503986 -0.14254654]


In [6]:
#Numpy arccos() , arcsin() & arctan() method
#This function is used to calculate the inverse cos , sin & tan of the array elements
import numpy as np
arr = [0 , 0.3 , -1]
print(arr)
x = np.arccos(arr)
print(x)
x = np.arcsin(arr)
print(x)
x = np.arctan(arr)
print(x)

[0, 0.3, -1]
[1.57079633 1.26610367 3.14159265]
[ 0.          0.30469265 -1.57079633]
[ 0.          0.29145679 -0.78539816]


In [7]:
#Numpy degree() method
#This function is used to convert the angles from radian to degrees

import numpy as np
import math

arr = [1,2,3]
print(arr)
degval = np.degrees(arr)
print(degval)

[1, 2, 3]
[ 57.29577951 114.59155903 171.88733854]


In [10]:
#Numpy deg2rad() method
#This function is used to convert the angles from degree to radian
import numpy as np
arr = [1,2,3]
print(arr)
degval = np.deg2rad(arr)
print(degval)

[1, 2, 3]
[0.01745329 0.03490659 0.05235988]


In [15]:
#Numpy rad2deg() method

import numpy as np
import math

arr = [0 , 1 , 5]
print("Input arr : \n" , arr)

degval = np.rad2deg(arr)
print("\n Degree Value: \n" , degval)

Input arr : 
 [0, 1, 5]

 Degree Value: 
 [  0.          57.29577951 286.47889757]


In [16]:
#Numpy radians() method
import numpy as np

arr = [0 , 30 , 60 , 90]
print("Input array : \n" , arr)

radval = np.radians(arr)
print("\n Radian value: \n" , radval)

Input array : 
 [0, 30, 60, 90]

 Radian value: 
 [0.         0.52359878 1.04719755 1.57079633]


In [13]:
#Numpy hypot() method
#This function is used to calculate the hypotenude for the right angled triangle.
#The hypotenuese of the right anfle triangle calculated as:
#h = sqrt(b^2 + p^2)
#where b & p are base & perpendicular of right angle triangle

#Each value of h is copied into the output array

import numpy as np

base = [10 , 2 , 5 , 50]
per = [3 , 10 , 23 , 6]


print("Input base array:" , base)
print("Input perpendicular array:" , per)

hyp = np.hypot(base , per)
print("hypotenuse: " , hyp)

Input base array: [10, 2, 5, 50]
Input perpendicular array: [3, 10, 23, 6]
hypotenuse:  [10.44030651 10.19803903 23.53720459 50.35871325]


In [19]:
#Numpy ceil() , Floor() , round()
#This function returns the ceil value of the input array elements. The floor of a number x is i

#Numpy rint()
#This function is used to round the array elements to the nearest integer

arr = [0.23 , 0.69 , 1.2 , 1.24 , 9.99 , 7.7]
print("Input Array: " , arr)
print("Ceil value: " , np.ceil(arr))
print("Floor value: " , np.floor(arr))
print("Round value: " , np.round(arr))
print("Rint value: " , np.rint(arr))

Input Array:  [0.23, 0.69, 1.2, 1.24, 9.99, 7.7]
Ceil value:  [ 1.  1.  2.  2. 10.  8.]
Floor value:  [0. 0. 1. 1. 9. 7.]
Round value:  [ 0.  1.  1.  1. 10.  8.]
Rint value:  [ 0.  1.  1.  1. 10.  8.]


In [20]:
#Numpy fix()
#This function is used to round the array values to the nearest integers towards zero.

import numpy as np

arr = [0.23 , 0.09 , 1.2 , 1.24 , 9.99]

print("Input array: " , arr)

r_arr = np.fix(arr)

print('Ouput array: ' , r_arr)

Input array:  [0.23, 0.09, 1.2, 1.24, 9.99]
Ouput array:  [0. 0. 1. 1. 9.]


In [21]:
#Numpy trunc()
#The function returns the truncated value of the input array elements
#The truncated value t of input value x is the nearest integer closer to zero then x
#The fractional part of the input number is discarded by this function

import numpy as np
arr = [0.23 , 0.09 , 1.2 , 1.24 , 9.99]

print("Input array: " , arr)

r_arr = np.trunc(arr)

print("Output array: " , r_arr)

Input array:  [0.23, 0.09, 1.2, 1.24, 9.99]
Output array:  [0. 0. 1. 1. 9.]
