<a href="https://colab.research.google.com/github/Architag1503/Colab/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a general purpose array processing package/libraray. It provides a high performance multidimensional array object and tools for working with these arrays.

It is fundamental package for scientific computing with python. It contain various features including these important ones.

Numpy's main object is the homogeneous multidimensional array.

It is table of all elements all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is a rank. Numpy array class is class ndarray. It is also known by the alias array.

In [2]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3] , [4,5,6]])
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)


<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [ ]:
a = np.array([[1,2,3] , [4,5,6]] , dtype = 'float')
print(a.dtype)

float64


In [ ]:
b = np.array(((1,2,3) , (4,5,6)))
print(b.dtype)

int64


In [ ]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
d = np.full((3,3) , 6 , dtype = 'complex')
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [ ]:
e = np.random.random((2,2))
print(e)

[[0.16197556 0.13745714]
 [0.67693983 0.67216669]]


In [4]:
f = np.arange(0 , 30, 5);
print(f)

[ 0  5 10 15 20 25]


Breaking the range in x parts can be done by using linspace format .linspace(start , end , x)

In [10]:
g = np.linspace(0,30,5)
print(g)

[ 0.   7.5 15.  22.5 30. ]


reshape function is used to reshape the array means convert 2D array to 3D array and syntax is arr.reshape(x,y,z,..) giving dimensions in it.

In [11]:
arr = np.array([[2,3,12,6],
               [7,6,8,13],
                [11,56,23,1]])
newarr = arr.reshape(2,2,3)

In [12]:
print(arr)
print(newarr)

[[ 2  3 12  6]
 [ 7  6  8 13]
 [11 56 23  1]]
[[[ 2  3 12]
  [ 6  7  6]]

 [[ 8 13 11]
  [56 23  1]]]


.flatten function is used to convert any dimension array into 1D array

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
flarr = arr.flatten()
print(arr)
print(flarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


slicing is a way to extract a subsequence (like a part of a list, tuple, string, or any sequence type) from a sequence. It allows you to select elements by specifying start, stop, and step indices.

sequence[start:stop:step]
Where:

start → index to start the slice (inclusive, default is 0)

stop → index to end the slice (exclusive)

step → how many steps to jump between elements (default is 1)

In [8]:
arr = np.array([[1,2,3,4],
                [4,5,6,7],
                [8,7,6,5]])

temp = arr[0:3:2]
print(arr)
print(temp)

[[1 2 3 4]
 [4 5 6 7]
 [8 7 6 5]]
[[1 2 3 4]
 [8 7 6 5]]


In [9]:
arr = np.array([[1,2,3,4],
                [4,5,6,7],
                [8,7,6,5]])

temp = arr[:2 ,:2] #first factor represent end row and second represent end column
print(arr)
print(temp)

[[1 2 3 4]
 [4 5 6 7]
 [8 7 6 5]]
[[1 2]
 [4 5]]


In [10]:
print(arr + 1) #It will add automatically add 1 to each value in arr

[[2 3 4 5]
 [5 6 7 8]
 [9 8 7 6]]


In [11]:
print(arr - 1) #It will add automatically subtract 1 to each value in arr

[[0 1 2 3]
 [3 4 5 6]
 [7 6 5 4]]


In [12]:
print(arr * 2) #It will add automatically multiply 2 to each value in arr

[[ 2  4  6  8]
 [ 8 10 12 14]
 [16 14 12 10]]


In [14]:
print(arr * arr) #It will add automatically do square of each value in arr
print(arr**2) # ** represent the power symbol so this will also so sqaure of each element

[[ 1  4  9 16]
 [16 25 36 49]
 [64 49 36 25]]
[[ 1  4  9 16]
 [16 25 36 49]
 [64 49 36 25]]


In [15]:
z = np.array([[2,3,12,7],
              [4,5,6,54],
              [6,5,34,3]])
print(z);
print(z.T)# this is use to transpose the array

[[ 2  3 12  7]
 [ 4  5  6 54]
 [ 6  5 34  3]]
[[ 2  4  6]
 [ 3  5  5]
 [12  6 34]
 [ 7 54  3]]


In [22]:
print(z.max())
print(z.min())
print(z.max(axis=0)) # axis 1 means maximums in rows and axis 0 means maximum in colums
print(z.min(axis=1))
print(z.sum())
print(z.sum(axis=0))
print(z.sum(axis=1))

54
2
[ 6  5 34 54]
[2 4 3]
141
[12 13 52 64]
[24 69 48]


In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

print(a+b);
print(a*b);
print(a**b);
print(a.dot(b))

[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]
[[  1   4]
 [ 27 256]]
[[ 7 10]
 [15 22]]


In [25]:
print(np.cos(a))
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [26]:
#Python program to demonstrate sorting in numpy
import numpy as np

a = np.array([[1,4,2],
              [3,4,6],
              [0,-1,5]])

#sorted array
print("Array elements in sorted order:\n" , np.sort(a , axis=None))

#sort array row-wise
print("Row-wise sorted array:\n" , np.sort(a , axis=1))



Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [27]:
#specify sort algorithm
print("Column wise sort by applying merge-sort:\n" , np.sort(a , axis=0 , kind='mergesort'))



Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [30]:
#Example to show sorting of structured array
#set alias names for dtypes
dtypes = [('name' , 'S10') , ('grad_year', int) , ('cgpa' , float)]

#Values put in the array
values = [('Hrithik' , 2009, 8.5) , ('Ajay' , 2008  , 9.7) ,
          ('Pankaj' , 2008 , 7.9) , ('Akash' , 2009 , 9.0)]

#Creating array
arr = np.array(values , dtype=dtypes)

print("\nArray sorted by names:\n" , np.sort(arr , order='name'))
print("\nArray sorted by graduation year\n" , np.sort(arr , order='grad_year'))
print("\nArray sorted by cgpa\n" , np.sort(arr , order="cgpa"))
print("\nArray sorted by graduation year then cgpa\n" , np.sort(arr , order=["grad_year" , "cgpa"]))



Array sorted by names:
 [(b'Ajay', 2008, 9.7) (b'Akash', 2009, 9. ) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]

Array sorted by graduation year
 [(b'Ajay', 2008, 9.7) (b'Pankaj', 2008, 7.9) (b'Akash', 2009, 9. )
 (b'Hrithik', 2009, 8.5)]

Array sorted by cgpa
 [(b'Pankaj', 2008, 7.9) (b'Hrithik', 2009, 8.5) (b'Akash', 2009, 9. )
 (b'Ajay', 2008, 9.7)]

Array sorted by graduation year then cgpa
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 9.7) (b'Hrithik', 2009, 8.5)
 (b'Akash', 2009, 9. )]
